# docker-compose.yml

version: '3.8'

services:
  # The Node.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    # Environment variables for the application
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/trip-planner
      - JWT_SECRET=your_jwt_secret_for_docker # Use a different secret for Docker environment
      - JWT_EXPIRE=30d
      - NODE_ENV=production
    # The application service depends on the mongo service
    depends_on:
      - mongo

  # The MongoDB database service
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    # Persist database data using a volume
    volumes:
      - mongo-data:/data/db

volumes:
  # Define the mongo-data volume
  mongo-data: